name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@boardJestTest
      with:
        fetch-depth: 2

    - name: Set up Node.js v10.5.0
      uses: actions/setup-node@v1
      with:
          node-version: 10.5.0

    - name: Install dependencies
      run: npm install --force

    - name: Run tests
      run: npm test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
