name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js v20.12.2
      uses: actions/setup-node@v1
      with:
          node-version: 20.12.2

    - name: Install dependencies
      run: npm install --force

    - name: Run tests
      run: npm test --bail=false

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
