name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js v20.12.2
      uses: actions/setup-node@v1
      with:
          node-version: 20.12.2

    - name: Install dependencies
      run: npm install --force


    - name: Run tests
      run: npm run --silent test 

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      
    - name: Create Codecov comment
      uses: ArtiomTr/jest-coverage-report-action@v2
      with: 
        test-script: npm test

    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
